export const LOGIN_USER = 'LOGIN_USER';
export const IS_LOGGED_IN = 'IS_LOGGED_IN';
export const SIGNOUT_USER = 'SIGNOUT_USER';

export const FETCH_POKEMONS_REQUEST = 'FETCH_POKEMONS_REQUEST';
export const FETCH_POKEMONS_FAILURE = 'FETCH_POKEMONS_FAILURE';
export const FETCH_POKEMONS_SUCCESS = 'FETCH_POKEMONS_SUCCESS';

export const SET_CURRENT_POKEMON = 'SET_CURRENT_POKEMON';
